# Generated by Django 5.2.4 on 2025-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0002_alter_user_options_rename_color_bike_bike_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_use', 'In Use'), ('returned', 'Returned'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('offline', 'Offline / Inactive')], default='available', max_length=20),
        ),
    ]
