# Generated by Django 5.2.4 on 2025-07-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0003_bike_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='is_available',
        ),
    ]
