# Generated by Django 5.2.4 on 2025-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0004_remove_bike_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
