# Generated by Django 5.2.4 on 2025-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
