# Generated by Django 5.2.4 on 2025-07-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
