# Generated by Django 5.2.4 on 2025-07-31 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0007_bike_returned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='returned_at',
        ),
    ]
