# Generated by Django 5.2.4 on 2025-07-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0008_remove_bike_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_use', 'In Use')], default='available', max_length=20),
        ),
    ]
