# Generated by Django 5.2.4 on 2025-07-31 05:31

from django.db import migrations

def update_bike_statuses(apps, schema_editor):
    Bike = apps.get_model('rental_api', 'Bike')
    
    # Update bikes with old statuses to new simplified statuses
    Bike.objects.filter(status='returned').update(status='available')
    Bike.objects.filter(status='maintenance').update(status='available')
    Bike.objects.filter(status='reserved').update(status='available')
    Bike.objects.filter(status='offline').update(status='available')

def reverse_update_bike_statuses(apps, schema_editor):
    # This migration is not reversible as we're simplifying the status system
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0009_alter_bike_status'),
    ]

    operations = [
        migrations.RunPython(update_bike_statuses, reverse_update_bike_statuses),
    ]
