# Generated by Django 5.2.4 on 2025-07-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0011_alter_bike_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for this bike', max_length=15, null=True),
        ),
    ]
