# Generated by Django 5.2.4 on 2025-07-31 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0012_bike_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('browse_bikes_clicked', 'Browse Bikes Clicked'), ('about_page_visited', 'About Page Visited'), ('contact_clicked', 'Contact Clicked'), ('feature_clicked', 'Feature Clicked')], max_length=50)),
                ('page', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
