# Generated by Django 5.2.4 on 2025-07-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0013_analytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
    ]
