# Generated by Django 5.2.4 on 2025-07-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0015_user_full_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
