# Generated by Django 5.2.4 on 2025-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0017_booking_actual_end_time_booking_actual_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
