# Generated by Django 5.2.4 on 2025-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0018_alter_booking_end_time_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
